main:
  - name: About
    url: '#about'
    weight: 1
  - name: Bitcoin
    url: /bitcoin/
    weight: 2
  - name: Books
    url: /books/
    weight: 3
  - name: AI
    url: /AI/
    weight: 4
  - name: Notes
    url: /notes/
    weight: 5
  - name: Web
    url: /web-development/
    weight: 6